# Generated by Django 2.2.2 on 2019-06-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Com',
        ),
    ]
