# Generated by Django 2.1.15 on 2020-01-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200112_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='octocat.png', upload_to='post_images'),
        ),
    ]
