# Generated by Django 2.1.15 on 2020-02-09 01:35

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200119_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile_image'),
        ),
    ]
