# Generated by Django 2.1.15 on 2020-02-19 15:26

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200209_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='octocat.png', upload_to='profile_image'),
        ),
    ]
