# Generated by Django 3.0.5 on 2020-04-08 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200319_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed,no spaces and minimum 10 digits.", regex='^\\+?1?\\d{10,15}$')]),
        ),
    ]
