# Generated by Django 2.2.2 on 2019-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
