# Generated by Django 2.2.2 on 2019-06-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190608_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='com',
            name='id',
        ),
        migrations.AlterField(
            model_name='com',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
