# Generated by Django 2.1.15 on 2020-02-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20190608_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='com',
            name='discripton',
            field=models.TextField(default='Test'),
        ),
    ]
