# Generated by Django 2.1.15 on 2020-02-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_com_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='com',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
